export const colorTokens = {
  shellBackground: '#f8fafc',
  shellSurface: '#ffffff',
  shellSurfaceDense: '#f1f5f9',
  shellBorder: '#d1d5db',
  shellBorderMuted: '#e5e7eb',
  textPrimary: '#111827',
  textSecondary: '#4b5563',
  textMuted: '#6b7280',
  accentSurface: '#ede9fe',
  accentBorder: '#c4b5fd',
  accentText: '#4c1d95',
  buttonSurface: '#f8fafc',
  buttonBorder: '#cbd5e1',
  buttonDisabledSurface: '#e5e7eb',
  buttonDisabledText: '#6b7280',
} as const;
