import type { AppState } from '@/store/state';

export const representativeScenario: AppState = {
  schemaVersion: 1,
  entities: {
    bills: {
      allIds: ['bill_rent', 'bill_power', 'bill_netflix', 'bill_auto'],
      byId: {
        bill_rent: {
          id: 'bill_rent',
          name: 'Rent',
          category: 'Housing',
          expectedAmount: 1450,
          frequency: 'monthly',
          nextDueDate: '2026-04-05',
          autopayEnabled: false,
          classification: 'fixed',
          priority: 'essential',
          state: 'active',
        },
        bill_power: {
          id: 'bill_power',
          name: 'Power',
          category: 'Utilities',
          expectedAmount: 190,
          frequency: 'monthly',
          nextDueDate: '2026-04-16',
          autopayEnabled: true,
          classification: 'variable',
          priority: 'essential',
          renewalBehavior: 'monthly utility cycle',
          state: 'active',
        },
        bill_netflix: {
          id: 'bill_netflix',
          name: 'Netflix',
          category: 'Subscriptions',
          expectedAmount: 22,
          frequency: 'monthly',
          nextDueDate: '2026-04-20',
          autopayEnabled: true,
          classification: 'fixed',
          priority: 'optional',
          renewalBehavior: 'monthly renewal',
          state: 'active',
        },
        bill_auto: {
          id: 'bill_auto',
          name: 'Auto Insurance',
          category: 'Insurance',
          expectedAmount: 780,
          frequency: 'semiannual',
          nextDueDate: '2026-06-01',
          autopayEnabled: false,
          classification: 'fixed',
          priority: 'essential',
          renewalBehavior: 'semiannual renewal',
          state: 'active',
        },
      },
    },
    payments: {
      allIds: ['pay_1', 'pay_2', 'pay_3', 'pay_4', 'pay_5'],
      byId: {
        pay_1: {
          id: 'pay_1',
          billId: 'bill_rent',
          amount: 1450,
          paymentDate: '2026-04-03',
          paymentType: 'manual',
        },
        pay_2: {
          id: 'pay_2',
          billId: 'bill_power',
          amount: 210,
          paymentDate: '2026-04-02',
          paymentType: 'autopay',
        },
        pay_3: {
          id: 'pay_3',
          billId: 'bill_netflix',
          amount: 22,
          paymentDate: '2026-03-20',
          paymentType: 'autopay',
        },
        pay_4: {
          id: 'pay_4',
          billId: 'bill_power',
          amount: 180,
          paymentDate: '2026-03-02',
          paymentType: 'autopay',
        },
        pay_5: {
          id: 'pay_5',
          billId: 'bill_auto',
          amount: 740,
          paymentDate: '2025-12-01',
          paymentType: 'manual',
        },
      },
    },
  },
  forecastSettings: {
    monthlyIncomeAssumption: 4200,
    includeVariableEstimates: true,
    forecastHorizonMonths: 3,
    payScheduleAssumption: 'monthly',
  },
  preferences: {
    themeMode: 'system',
    accentPreference: 'dusty-plum',
    backgroundPreference: 'default',
    defaultSort: 'nextDueDate',
    defaultFilter: 'all',
    densityMode: 'comfortable',
  },
  ui: {
    activeDestination: 'dashboard',
    selectedBillId: null,
    editing: {
      kind: 'none',
      selectedPaymentId: null,
    },
    billsWorkspace: {
      searchQuery: '',
      activeFilter: 'all',
      sortKey: 'nextDueDate',
    },
  },
};
